{{- if .Values.volume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dirigible.fullname" . }}-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.volume.storage }}
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dirigible.fullname" . }}
  labels:
    {{- include "dirigible.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dirigible.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dirigible.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dirigible.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.volume.enabled }}
          volumeMounts:
          - name: {{ include "dirigible.fullname" . }}-volume
            mountPath: /usr/local/tomcat/target/dirigible
          {{- end }}
          env:
            - name: DIRIGIBLE_HOST
              value: https://{{ .Release.Name }}.{{ $.Values.apirule.host }}
            {{- if .Values.keycloak.enabled }}
            - name: KEYCLOAK_CONFIDENTIAL_PORT
              value: "443"
            - name: KEYCLOAK_SSL_REQUIRED
              value: "none"
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.relam }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.clientId }}
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: https://{{ .Values.keycloak.name }}.{{ .Values.apirule.host }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.keycloak.enabled }}
          image: "{{ .Values.image.repositoryKeycloak }}:{{ .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /
              port: http
          readinessProbe:
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /services/v4/healthcheck
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.volume.enabled }}
      volumes:
        - name: {{ include "dirigible.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "dirigible.fullname" . }}-claim
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "dirigible.fullname" . }}
  labels:
    {{- include "dirigible.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dirigible.selectorLabels" . | nindent 4 }}

---

{{- if .Values.apirule.enabled -}}
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ include "dirigible.fullname" . }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: {{ .Values.apirule.host }}
    name: {{ include "dirigible.fullname" . }}
    port: {{ .Values.service.port }}
{{- end }}