name: Build

on:
  push:
    branches: 
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Maven Build
      run: mvn clean install
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Push Anonymous
      run: |
        cd releng/anonymous-all
        docker build -t dirigible-base-platform-anonymous -f Dockerfile-base .
        docker tag dirigible-base-platform-anonymous dirigiblelabs/dirigible-base-platform-anonymous
        docker push dirigiblelabs/dirigible-base-platform-anonymous
        docker build -t dirigible-anonymous .
        docker tag dirigible-anonymous dirigiblelabs/dirigible-anonymous
        docker push dirigiblelabs/dirigible-anonymous
        cd ../../
    - name: Push Anonymous - Runtime
      run: |
        cd releng/anonymous-runtime
        docker build -t dirigible-base-platform-runtime-anonymous -f Dockerfile-base .
        docker tag dirigible-base-platform-runtime-anonymous dirigiblelabs/dirigible-base-platform-runtime-anonymous
        docker push dirigiblelabs/dirigible-base-platform-runtime-anonymous
        docker build -t dirigible-runtime-anonymous .
        docker tag dirigible-runtime-anonymous dirigiblelabs/dirigible-runtime-anonymous
        docker push dirigiblelabs/dirigible-runtime-anonymous
        cd ../../
